#!/usr/bin/env -S awk -f
NR==1 {
	# default [0,1] interval
	for(i = 1; i <= NF; i++) {
		x[i,1] = 0
		x[i,2] = 1
	}

	# i.e. rescale column 1 to [0,1] (no-op)
	x[1,1] = 0; x[1,2] = 1;
}

{
	for(i = 1; i <= NF; i++) {
		printf "%.5f ", (x[i,2] - x[i,1]) * $i + x[i,1]
	}
	printf "\n"
}
